# Setup
name:         George Woods
tagline:      Customer Engineer - Global Technical Team at Micrsoft
baseurl:      "jekyll-architect-theme/"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
